データの保存を PostgreSQL ni
Akkkky/frankly-note pull request #10
Opened 2021-01-24 13:37 UTC by Akkkky

2021-01-30 08:10 UTC, komagata requested changes

2021-01-30 08:10 UTC, komagata commented on app.rb
>  enable :method_override
これはデフォルトでenableだったと思います。

2021-01-30 08:10 UTC, komagata commented on app.rb
>  post '/compose' do
HTTP Verb（GETとかPOST）が動詞でURLは名詞というのが基本ですので名詞の何にPOSTするのか考えてみてください〜

2021-01-30 08:10 UTC, komagata commented on lib/crud_controller.rb
> +  TABLE_NAME = 'sinatra_table'
定数だとDB名もテーブル名も変更ができないのでインスタンス変数にして変更できるようにした方がいいかもです〜

2021-01-31 04:04 UTC, ot0m1 commented on app.rb
>  enable :method_override
http://sinatrarb.com/intro.html
そのようでした！

![スクリーンショット 2021-01-31 13 00 55](https://user-images.githubusercontent.com/6190966/106374234-6558f280-63c4-11eb-8a38-5dabce60ccd4.png)

また、最近のブラウザだと基本 PUT / DELETE メソッドはサポートされているようでした。

https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/PUT
https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/DELETE

`method_override`を明記しなくても自環境での動作が確認できたため、削除しました。

2021-01-31 04:10 UTC, ot0m1 commented on app.rb
>  post '/compose' do
この辺りが曖昧になっていました。ご指摘ありがとうございます！
`composition` に変更しました。

なおメモ作成時のリソース名が `new` などではなく `composition` なのは、Sinatra → フランク・シナトラ → メモ作成を作曲というようにしたい、というコンセプトからの命名です。

2021-01-31 04:11 UTC, ot0m1 commented on app.rb
> -get '/edit/note/:id' do
ここも動詞だったので `editing` に変更。

2021-01-31 04:11 UTC, ot0m1 commented on app.rb
> +get '/editing/note/:id' do
ここも動詞だったので `editing` に変更。

2021-01-31 04:13 UTC, ot0m1 commented on app.rb
> +  erb :index
`views` ディレクトリに格納されるテンプレートファイルは、テンプレートの内容を書き出すため、動詞のファイル名になるのが妥当だと考え `index` に変更。

2021-01-31 04:15 UTC, ot0m1 commented on lib/crud_controller.rb
> +  TABLE_NAME = 'sinatra_table'
処理中に変わらない値であるため定数で指定していました。

ですが利用者の環境によって変わり得る値であるため、利用者が変更できるようDB名とテーブル名をインスタンス変数にしてクラスオブジェクト作成の際に引数で受け取るように変更しました。

2021-02-01 06:04 UTC, komagata commented on app.rb
>  enable :method_override
modularスタイルだと書く必要があるんですよね！

2021-02-01 06:07 UTC, komagata requested changes

2021-02-01 06:07 UTC, komagata commented on app.rb
> +post '/composition' do
他のURLからすると`post '/note'`とかの方がいい気がします〜

2021-02-01 06:07 UTC, komagata commented on views/index.erb
> +<div class="notes-list"><%= @notes_in_ul_tag %></div>
最終行に改行がないようです〜

2021-02-01 12:46 UTC, ot0m1 commented on views/index.erb
> +<div class="notes-list"><%= @notes_in_ul_tag %></div>
ファイル最終行の改行は rubocop で自動修正されると思い込んでおり、チェックがおろそかになっていました🙇‍♂️
改めて確認したら rubocop では修正されないので、他のファイルも確認し修正しました。

何度もブートキャンプ内でも指摘を見聞きする部分なのに、確認が甘かったです。
今までエディタ側で設定しなかったので、併せて保存時に自動で最終行に改行が入るよう設定しました。

2021-02-01 12:53 UTC, ot0m1 commented on app.rb
> +post '/composition' do
確かに作成するリソースは `note` なので、post 先は  `note`  が妥当だと考え修正しました。

2021-02-02 05:19 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

発展的な話題としては、sinatraのアプリ側のコードは変わらず、ファイル処理用のクラスとDB処理用のクラスを差し替えるだけでこの変更に対応できるように作ってあるといいのでそれを目指すといい感じです。

（これができているとデータのアクセス部分が「抽象化できている」みたいにいいます）

2021-02-02 13:37 UTC, merged